export declare const color: {
    main_green_5: string;
    main_green_10: string;
    main_green_20: string;
    red_5_light: string;
    red_10_light: string;
    red_20_light: string;
    red_5_dark: string;
    grey_5_light: string;
    grey_10_light: string;
    grey_20_light: string;
    grey_30_light: string;
    grey_40_light: string;
    grey_50_light: string;
    grey_60_light: string;
    grey_70_light: string;
    grey_80_light: string;
    grey_5_dark: string;
    grey_10_dark: string;
    grey_20_dark: string;
    grey_30_dark: string;
    grey_40_dark: string;
    grey_50_dark: string;
    grey_60_dark: string;
    grey_70_dark: string;
    grey_80_dark: string;
};
export type Color = keyof typeof color;
