name: version-setter
description: 'set version variables'

outputs:
  main_version:
    description: 'main_version'
    value: ${{ steps.version.outputs.main_version }}
  new_version:
    description: 'new_version'
    value: ${{ steps.new_version.outputs.new_version }}
  alpha_version:
    description: 'alpha_version'
    value: ${{ steps.new_version.outputs.alpha_version }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Main and Alpha Version
      id: version
      shell: bash
      run: |
        MAIN_VERSION=$(yarn --silent run version)
        echo "main_version=$MAIN_VERSION" >> $GITHUB_OUTPUT

    - name: New Version
      id: new_version
      shell: bash
      run: |
        semver=$(bash .script/get-version-semver.sh '${{ github.event.pull_request.title }}')
        yarn version $semver --no-git-tag-version
        NEW_VERSION=$(yarn --silent run version)
        ALPHA_VERSION=$NEW_VERSION-alpha${{ github.event.pull_request.number }}
        echo "alpha_version=$ALPHA_VERSION" >> $GITHUB_OUTPUT
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
