name: Clear Alpha

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:

concurrency:
  group: 'pages-deploy'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      main_version: ${{ steps.version.outputs.main_version }}
      alpha_version: ${{ steps.version.outputs.alpha_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/version-setter
        id: version

  clear:
    needs: version
    runs-on: ubuntu-latest
    env:
      main_version: ${{ needs.version.outputs.main_version }}
      alpha_version: ${{ needs.version.outputs.alpha_version }}
      new_version: ${{ needs.version.outputs.new_version }}
    steps:
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: pages
          path: pages

      - name: Remove Alpha Pages
        run: |
          rm -rf pages/alpha_version

          cd pages
          git config --global user.name 'deploy'
          git config --global user.email 'deploy@users.noreply.github.com'
          git add .
          git commit -m "Remove Alpha $alpha_version"
          git push

      - name: Comment a pull_request
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"Alpha $alpha_version Removed\"}"
