# This is a basic workflow to help you get started with Actions

name: Clear Alpha

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:

jobs:
  clear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: pages
          path: pages
      - name: Generate Pages
        run: |
          VERSION=alpha-pr${{ github.event.pull_request.number }}
          rm -rf $GITHUB_WORKSPACE/pages/$VERSION
      - name: Commit & Push
        run: |
          VERSION=alpha-pr${{ github.event.pull_request.number }}
          cd pages
          git config --global user.name 'deploy'
          git config --global user.email 'deploy@users.noreply.github.com'
          git add .
          git status
          git commit -m "Removed Alpha $VERSION"
          git pull
          git push
      - name: Comment a pull_request
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          VERSION=alpha-pr${{ github.event.pull_request.number }}
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"Alpha $VERSION Removed\"}"
