name: Clear Alpha

on:
  pull_request:
    branches: [main]
    types: [closed]

  workflow_dispatch:

concurrency:
  group: 'pages-deploy'

jobs:
  clear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: pages
          path: pages

      - name: Set Version Variables
        run: |
          MAIN_VERSION=$(cd $GITHUB_WORKSPACE/branch && yarn --silent run version)
          ALPHA_VERSION=$MAIN_VERSION-alpha${{ github.event.pull_request.number }}
          echo "main_version=$MAIN_VERSION" >> $GITHUB_ENV
          echo "alpha_version=$MAIN_VERSION" >> $GITHUB_ENV

      - name: Remove Alpha Pages
        env:
          alpha_version: ${{ env.alpha_version }}
          main_version: ${{ env.main_version}}
        run: |
          rm -rf pages/alpha_version

          bash .script/commit.sh "Remove Alpha $alpha_version"

      - name: Comment a pull_request
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          alpha_version: ${{ env.alpha_version }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"Alpha $alpha_version Removed\"}"
