name: Deploy Alpha

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: 'pages-deploy'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      main_version: ${{ steps.version.outputs.main_version }}
      alpha_version: ${{ steps.version.outputs.alpha_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Version
        id: version
        shell: bash
        run: |
          MAIN_VERSION=$(yarn --silent run version)
          echo "main_version=$MAIN_VERSION"
          echo "main_version=$MAIN_VERSION" >> $GITHUB_OUTPUT

          semver=$(bash .script/get-version-semver.sh '${{ github.event.pull_request.title }}')
          yarn version $semver --no-git-tag-version
          NEW_VERSION=$(yarn --silent run version)
          echo "new_version=$NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          ALPHA_VERSION=$NEW_VERSION-alpha${{ github.event.pull_request.number }}
          echo "alpha_version=$ALPHA_VERSION"
          echo "alpha_version=$ALPHA_VERSION" >> $GITHUB_OUTPUT

  build:
    needs: version
    runs-on: ubuntu-latest
    env:
      main_version: ${{ needs.version.outputs.main_version }}
      alpha_version: ${{ needs.version.outputs.alpha_version }}
      new_version: ${{ needs.version.outputs.new_version }}
      base_path: 'design'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Pages Repo
        uses: actions/checkout@v3
        with:
          repository: '42-world/42-world.github.io'
          path: .pages
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: CI
        run: |
          yarn
          yarn ci

      - name: Build Alpha Pages
        id: build
        run: |
          yarn
          NODE_ENV=production yarn build
          sha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          yarn version --new-version $alpha_version-$sha --no-git-tag-version
          yarn pack

          rm -rf .pages/$base_path/*-alpha${{ github.event.pull_request.number }}
          mkdir -p .pages/$base_path/$alpha_version
          cp -rf dist/* .pages/$base_path/$alpha_version
          cp -rf *.tgz .pages/$base_path/$alpha_version
          echo "pack_name=$(ls *.tgz)" >> $GITHUB_OUTPUT
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: Commit Alpha Pages
        id: deploy
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Alpha ${{ env.alpha_version }} Build (${{ steps.build.outputs.sha }})'
          commit_options: '--allow-empty'
          repository: .pages
          branch: main

      - name: Fetch Build Status Url
        id: fetch-build-status
        run: |
          url=$(bash .script/fetch-deploy-url.sh '${{ steps.deploy.outputs.commit_hash }}')
          echo "url=$url"
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Comment PR Alpha Build
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Alpha ${{ env.alpha_version }} - ${{ steps.build.outputs.sha }}

            _wait for the deploy to be done [here](${{ steps.fetch-build-status.outputs.url }})_

            ### Check it out!

            - Go to [StoryBook](https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/storybook)
            - Go to [Framer](https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/framer/components/Text/Text.framer.js)

            ### Or you can try...

            ```
            yarn add @42world/design-core@https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/${{ steps.build.outputs.pack_name }}
            ```
          comment_tag: execution

      - name: Comment commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ## Alpha ${{ env.alpha_version }} Rebuilt - ${{ steps.build.outputs.sha }}

            _wait for the deploy to be done [here](${{ steps.fetch-build-status.outputs.url }})_

            ### Check it out!

            - Go to [StoryBook](https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/storybook)
            - Go to [Framer](https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/framer/components/Text/Text.framer.js)

            ### Or you can try...

            ```
            yarn add @42world/design-core@https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/${{ steps.build.outputs.pack_name }}
            ```
