# This is a basic workflow to help you get started with Actions

name: Deploy Alpha

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # All commits, so we can look at the tags
          path: branch
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          ref: pages
          path: pages
      - name: Reset Pages
        run: |
          cd branch
          MAIN_VERSION=$(yarn --silent run version)
          cd ../pages
          VERSION=alpha-pr${{ github.event.pull_request.number }}
          rm -rf $VERSION
          cp -rf $MAIN_VERSION $VERSION
          git config --global user.name 'deploy'
          git config --global user.email 'deploy@users.noreply.github.com'
          git add .
          git status
          git commit -m "Reset Alpha $VERSION" | cat
      - name: Generate Pages
        run: |
          cd branch
          yarn
          yarn run build
          VERSION=alpha-pr${{ github.event.pull_request.number }}
          rm -rf $GITHUB_WORKSPACE/pages/$VERSION
          cp -rf dist $GITHUB_WORKSPACE/pages/$VERSION
      - name: Commit & Push
        run: |
          cd pages
          git config --global user.name 'deploy'
          git config --global user.email 'deploy@users.noreply.github.com'
          git add .
          VERSION=alpha-pr${{ github.event.pull_request.number }}
          bash $GITHUB_WORKSPACE/branch/.script/get-build-complete-message.sh $VERSION > $GITHUB_WORKSPACE/comment.txt
          git status
          git commit -m "Updated Alpha $VERSION" | cat
          git push --force
      - name: Comment a pull_request
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"$(cat $GITHUB_WORKSPACE/comment.txt)\"}"
