name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: 'pages-deploy'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      main_version: ${{ steps.version.outputs.main_version }}
      alpha_version: ${{ steps.version.outputs.alpha_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/version-setter
        id: version

  clear:
    needs: version
    runs-on: ubuntu-latest
    env:
      main_version: ${{ needs.version.outputs.main_version }}
      alpha_version: ${{ needs.version.outputs.alpha_version }}
      new_version: ${{ needs.version.outputs.new_version }}
    steps:
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          repository: '42-world/cdn'
          path: pages

      - name: Remove Alpha Pages
        run: |
          rm -rf pages/alpha_version

          cd pages
          git pull
          git add .
          git commit --allow-empty --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m "Remove Alpha $alpha_version"
          git push

      - name: Comment a pull_request
        env:
          GITHUB_SHA: ${{ github.event.commits }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$REPO/commits/$GITHUB_SHA/comments \
            -d "{\"body\": \" Removed Alpha $alpha_version\n\"}"

  build:
    needs: [version, clear]
    runs-on: ubuntu-latest
    env:
      main_version: ${{ needs.version.outputs.main_version }}
      alpha_version: ${{ needs.version.outputs.alpha_version }}
      new_version: ${{ needs.version.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - name: Checkout Pages
        uses: actions/checkout@v2
        with:
          repository: '42-world/cdn'
          path: pages

      - name: Generate Pages
        run: |
          cd main
          yarn
          yarn build
          yarn version --new_version $new_version
          yarn pack
          cd $GITHUB_WORKSPACE

          rm -rf pages/$new_version
          mkdir -p pages/$new_version
          cp -rf main/dist/* pages/$new_version
          cp -rf main/*.tgz pages/$new_version

          cd pages
          git pull
          git add .
          git commit --allow-empty --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" -m "Deploy version $new_version"
          git push

      - name: Comment a pull_request
        env:
          GITHUB_SHA: ${{ github.event.commits }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/$REPO/commits/$GITHUB_SHA/comments \
            -d "{\"body\": \" New Version $new_version Build Done!\n\"}"
