name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: 'pages-deploy'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      main_version: ${{ steps.version.outputs.main_version }}
      alpha_version: ${{ steps.version.outputs.alpha_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/version-setter
        id: version

  clear:
    needs: version
    runs-on: ubuntu-latest
    env:
      main_version: ${{ needs.version.outputs.main_version }}
      alpha_version: ${{ needs.version.outputs.alpha_version }}
      new_version: ${{ needs.version.outputs.new_version }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout Pages
        uses: actions/checkout@v3
        with:
          repository: '42-world/42-world.github.io'

      - name: Remove Alpha Pages
        run: |
          rm -rf $alpha_version*

      - name: Commit Alpha Pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Remove Alpha ${{ env.alpha_version }}'
          commit_options: '--allow-empty'

  build:
    needs: [version, clear]
    runs-on: ubuntu-latest
    env:
      main_version: ${{ needs.version.outputs.main_version }}
      alpha_version: ${{ needs.version.outputs.alpha_version }}
      new_version: ${{ needs.version.outputs.new_version }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout Pages Repo
        uses: actions/checkout@v3
        with:
          repository: '42-world/42-world.github.io'
          path: .pages
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate Pages
        run: |
          yarn
          NODE_ENV=production yarn build
          yarn version --new_version $new_version
          yarn pack

          rm -rf .pages/$new_version
          mkdir -p .pages/$new_version
          cp -rf dist/* .pages/$new_version
          cp -rf *.tgz .pages/$new_version

      - name: Commit Pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Version ${{ env.new_version }} Build'
          commit_options: '--allow-empty'
          repository: .pages
          branch: main

      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Comment commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ## Version ${{ env.new_version }} Build Done!

            ### Check it out!

            - Go to [StoryBook](https://42-world.github.io/${{ env.new_version }}/storybook)
            - Go to [Framer](https://42-world.github.io/${{ env.new_version }}/framer/components/Text/Text.framer.js)

            ### Or you can try...

            ```
            yarn add @42world/design-core@${{ env.new_version }}
            ```

            or

            ```
            yarn add @42world/design-core@https://42-world.github.io/${{ env.new_version }}/42world-design-core-v${{ env.new_version }}.tgz
            ```
