name: Deploy Alpha

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: 'pages-deploy'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      main_version: ${{ steps.version.outputs.main_version }}
      alpha_version: ${{ steps.version.outputs.alpha_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/version-setter
        id: version

  build:
    needs: version
    runs-on: ubuntu-latest
    env:
      main_version: ${{ needs.version.outputs.main_version }}
      alpha_version: ${{ needs.version.outputs.alpha_version }}
      new_version: ${{ needs.version.outputs.new_version }}
      base_path: 'design'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Pages Repo
        uses: actions/checkout@v3
        with:
          repository: '42-world/42-world.github.io'
          path: .pages
          token: ${{ secrets.GH_TOKEN }}

      - name: Build Alpha Pages
        id: build
        run: |
          yarn
          NODE_ENV=production yarn build
          sha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          yarn version --new-version $alpha_version-$sha --no-git-tag-version
          yarn pack

          rm -rf .pages/$base_path/$alpha_version
          mkdir -p .pages/$base_path/$alpha_version
          cp -rf dist/* .pages/$base_path/$alpha_version
          cp -rf *.tgz .pages/$base_path/$alpha_version
          echo "pack_name=$(ls *.tgz)" >> $GITHUB_OUTPUT
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: Deploy Alpha Pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Alpha ${{ env.alpha_version }} Build (${{ steps.build.outputs.sha }})'
          commit_options: '--allow-empty'
          repository: .pages
          branch: main

      - name: Comment PR Alpha Build
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Alpha ${{ env.alpha_version }} Build Done! - ${{ steps.build.outputs.sha }}

            ### Check it out!

            - Go to [StoryBook](https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/storybook)
            - Go to [Framer](https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/framer/components/Text/Text.framer.js)

            ### Or you can try...

            ```
            yarn add @42world/design-core@https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/${{ steps.build.outputs.pack_name }}
            ```
          comment_tag: execution

      - name: Comment commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            ## Alpha ${{ env.alpha_version }} Rebuilt

            ### Check it out!

            - Go to [StoryBook](https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/storybook)
            - Go to [Framer](https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/framer/components/Text/Text.framer.js)

            ### Or you can try...

            ```
            yarn add @42world/design-core@https://42-world.github.io/${{ env.base_path }}/${{ env.alpha_version }}/${{ steps.build.outputs.pack_name }}
            ```
