name: Deploy Alpha

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: 'pages-deploy'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      main_version: ${{ steps.version.outputs.main_version }}
      alpha_version: ${{ steps.version.outputs.alpha_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/version-setter
        id: version

  build:
    needs: version
    runs-on: ubuntu-latest
    env:
      main_version: ${{ needs.version.outputs.main_version }}
      alpha_version: ${{ needs.version.outputs.alpha_version }}
      new_version: ${{ needs.version.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: branch
      - name: Checkout Pages
        uses: actions/checkout@v3
        with:
          repository: '42-world/cdn'
          path: pages

      - name: Build Alpha Pages
        run: |
          cd branch
          yarn
          yarn build
          yarn version --new_version $alpha_version --no-git-tag-version
          yarn pack
          cd $GITHUB_WORKSPACE

          rm -rf pages/$alpha_version
          mkdir -p pages/$alpha_version
          cp -rf branch/dist/* pages/$alpha_version
          cp -rf branch/*.tgz pages/$alpha_version

          cd pages
          git config --global user.name 'deploy'
          git config --global user.email 'deploy@users.noreply.github.com'
          git pull
          git add .
          git commit -m "Updated Alpha $alpha_version"
          git push

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          reactions: rocket
          message: |
            ## Alpha ${{ env.alpha_version }} Build Done!

            Expected New Version: ${{ env.new_version }}

            ### Check it out!

            - Go to [StoryBook](https://42-world.github.io/cdn/${{ env.alpha_version }}/storybook)
            - Go to [Framer](https://42-world.github.io/cdn/${{ env.alpha_version }}/framer/index.js)

            ### Or you can try...

            ```
            yarn add @42world/design-core@https://42-world.github.io/cdn/${{ env.alpha_version }}/42world-design-core-v${{ env.main_version }}.tgz
            ```
          comment_tag: execution
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          reactions: rocket
          message: |
            Alpha ${{ env.alpha_version }} Rebuilt ${{ github.sha }}
